troiswa_back_first_page:
    path:     /test
    defaults: { _controller: TroiswaBackBundle:Main:test }
troiswa_back_prenom:
    path:     /prenom
    defaults: { _controller: TroiswaBackBundle:Main:prenom }
troiswa_back_theme:
    path:     /theme
    defaults: { _controller: TroiswaBackBundle:Main:theme }
troiswa_back_dashboard:
    path:     /dashboard
    defaults: { _controller: TroiswaBackBundle:Main:index }
troiswa_back_acteur:
    path:     /acteur
    defaults: { _controller: TroiswaBackBundle:Acteur:index }
troiswa_back_film:
    path:     /film
    defaults: { _controller: TroiswaBackBundle:Film:index }
troiswa_back_film_ajouter:
    path:     /film/ajouter
    defaults: { _controller: TroiswaBackBundle:Film:ajout }
troiswa_back_film_editer:
    path:     /film/editer/{id}
    defaults: { _controller: TroiswaBackBundle:Film:edit }
troiswa_back_categorie:
    path:     /categorie
    defaults: { _controller: TroiswaBackBundle:Categorie:index }
troiswa_back_acteur_ajouter:
    path:     /acteur/ajouter
    defaults: { _controller: TroiswaBackBundle:Acteur:ajout }
troiswa_back_acteur_editer:
    path:     /acteur/editer/{id}
    defaults: { _controller: TroiswaBackBundle:Acteur:edit }
troiswa_back_one_acteur:
    path:     /acteur/{id}
    defaults: { _controller: TroiswaBackBundle:Acteur:show }
